/* Additional record code for hel generated by the OpenModelica Compiler v1.13.0-dev-862-gceb595ee2 (64-bit). */

#include "meta/meta_modelica.h"

#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
}
#endif

