# Makefile generated by OpenModelica

# Simulations use -O3 by default
CC=gcc
CXX=g++
LINK=g++ -shared -Xlinker --export-all-symbols -fPIC
EXEEXT=.exe
DLLEXT=.dll
CFLAGS_BASED_ON_INIT_FILE=
DEBUG_FLAGS=-Os
CFLAGS=$(CFLAGS_BASED_ON_INIT_FILE) $(DEBUG_FLAGS) -falign-functions -msse2 -mfpmath=sse ${MODELICAUSERCFLAGS}   
CPPFLAGS= -I"C:/OpenModelica1.13.0-dev-64bit//include/omc/c" -I. -DOPENMODELICA_XML_FROM_FILE_AT_RUNTIME -DOMC_MODEL_PREFIX=CoffeeTemperature_Test_CoffeeTest11 -DOMC_NUM_MIXED_SYSTEMS=0 -DOMC_NUM_LINEAR_SYSTEMS=0 -DOMC_NUM_NONLINEAR_SYSTEMS=15 -DOMC_NDELAY_EXPRESSIONS=0 -DOMC_NVAR_STRING=0
LDFLAGS=-L"C:/OpenModelica1.13.0-dev-64bit//lib//omc" -L"C:/OpenModelica1.13.0-dev-64bit//lib" -Wl,--stack,16777216,-rpath,"C:/OpenModelica1.13.0-dev-64bit//lib//omc" -Wl,-rpath,"C:/OpenModelica1.13.0-dev-64bit//lib"   -lregex -lexpat -lomcgc -Wl,-Bstatic -lpthread -Wl,-Bdynamic -fopenmp -loleaut32 -limagehlp -lz -lhdf5  -lSimulationRuntimeC -lomcgc -lexpat -lregex -static-libgcc -luuid -loleaut32 -lole32 -limagehlp -lws2_32 -llis -lumfpack -lklu -lcolamd -lbtf -lamd -lsundials_idas -lsundials_kinsol -lsundials_nvecserial -lipopt -lcoinmumps -Wl,-Bstatic -lpthread -Wl,-Bdynamic -lm -lgfortranbegin -lgfortran -lmingw32 -lgcc_eh -lmoldname -lmingwex -lmsvcrt -luser32 -lkernel32 -ladvapi32 -lshell32 -lopenblas -lcminpack -lwsock32 -Wl,-Bstatic -lstdc++ -Wl,-Bdynamic 
DIREXTRA=-L"C:/Work/CAE/Modelica/OpenModelica/OpenModelica_Excel_Interface_ClassPackage/Examples/Test/parameterSweep/3"
MAINFILE=CoffeeTemperature.Test.CoffeeTest11.c
MAINOBJ=CoffeeTemperature.Test.CoffeeTest11.o
CFILES=CoffeeTemperature.Test.CoffeeTest11_functions.c CoffeeTemperature.Test.CoffeeTest11_records.c \
CoffeeTemperature.Test.CoffeeTest11_01exo.c CoffeeTemperature.Test.CoffeeTest11_02nls.c CoffeeTemperature.Test.CoffeeTest11_03lsy.c CoffeeTemperature.Test.CoffeeTest11_04set.c CoffeeTemperature.Test.CoffeeTest11_05evt.c CoffeeTemperature.Test.CoffeeTest11_06inz.c CoffeeTemperature.Test.CoffeeTest11_07dly.c \
CoffeeTemperature.Test.CoffeeTest11_08bnd.c CoffeeTemperature.Test.CoffeeTest11_09alg.c CoffeeTemperature.Test.CoffeeTest11_10asr.c CoffeeTemperature.Test.CoffeeTest11_11mix.c CoffeeTemperature.Test.CoffeeTest11_12jac.c CoffeeTemperature.Test.CoffeeTest11_13opt.c CoffeeTemperature.Test.CoffeeTest11_14lnz.c \
CoffeeTemperature.Test.CoffeeTest11_15syn.c CoffeeTemperature.Test.CoffeeTest11_16dae.c CoffeeTemperature.Test.CoffeeTest11_17inl.c 

OFILES=$(CFILES:.c=.o)
GENERATEDFILES=$(MAINFILE) CoffeeTemperature.Test.CoffeeTest11.makefile CoffeeTemperature.Test.CoffeeTest11_literals.h CoffeeTemperature.Test.CoffeeTest11_functions.h $(CFILES)

.PHONY: omc_main_target clean bundle

# This is to make sure that CoffeeTemperature.Test.CoffeeTest11_*.c are always compiled.
.PHONY: $(CFILES)

omc_main_target: $(MAINOBJ) CoffeeTemperature.Test.CoffeeTest11_functions.h CoffeeTemperature.Test.CoffeeTest11_literals.h $(OFILES)
	$(CC) -I. -o CoffeeTemperature.Test.CoffeeTest11$(EXEEXT) $(MAINOBJ) $(OFILES) $(CPPFLAGS) $(DIREXTRA)  "-LC:/OpenModelica1.13.0-dev-64bit//lib//omc" "-LC:/OpenModelica1.13.0-dev-64bit//lib/" "-L%APPDATA%/.openmodelica/binaries/Modelica" "-LC:/OpenModelica1.13.0-dev-64bit/lib/omlibrary/Modelica 3.2.2/Resources/Library/mingw64" "-LC:/OpenModelica1.13.0-dev-64bit/lib/omlibrary/Modelica 3.2.2/Resources/Library/win64" "-LC:/OpenModelica1.13.0-dev-64bit/lib/omlibrary/Modelica 3.2.2/Resources/Library" -lModelicaExternalC -lModelicaStandardTables -lModelicaIO -lModelicaMatIO -lzlib $(CFLAGS) $(CPPFLAGS) $(LDFLAGS)
clean:
	@rm -f CoffeeTemperature.Test.CoffeeTest11_records.o $(MAINOBJ)

bundle:
	@tar -cvf CoffeeTemperature.Test.CoffeeTest11_Files.tar $(GENERATEDFILES)