/* Additional record code for CoffeeTemperature.Test.CoffeeTest11 generated by the OpenModelica Compiler v1.13.0-dev-862-gceb595ee2 (64-bit). */

#include "meta/meta_modelica.h"

#ifdef __cplusplus
extern "C" {
#endif

#define CoffeeTemperature_CoffeeThermal_EnclosedConvection$enclosedConvection1_medium_FluidConstants__desc_added 1
const char* CoffeeTemperature_CoffeeThermal_EnclosedConvection$enclosedConvection1_medium_FluidConstants__desc__fields[28] = {"HCRIT0","SCRIT0","acentricFactor","casRegistryNumber","chemicalFormula","criticalMolarVolume","criticalPressure","criticalTemperature","deltah","deltas","dipoleMoment","hasAccurateConductivityData","hasAccurateViscosityData","hasAcentricFactor","hasCriticalData","hasDipoleMoment","hasFundamentalEquation","hasIdealGasHeatCapacity","hasLiquidHeatCapacity","hasSolidHeatCapacity","hasVapourPressureCurve","iupacName","meltingPoint","molarMass","normalBoilingPoint","structureFormula","triplePointPressure","triplePointTemperature"};
struct record_description CoffeeTemperature_CoffeeThermal_EnclosedConvection$enclosedConvection1_medium_FluidConstants__desc = {
  "CoffeeTemperature_CoffeeThermal_EnclosedConvection$enclosedConvection1_medium_FluidConstants", /* package_record__X */
  "CoffeeTemperature.CoffeeThermal.EnclosedConvection$enclosedConvection1.medium.FluidConstants", /* package.record_X */
  CoffeeTemperature_CoffeeThermal_EnclosedConvection$enclosedConvection1_medium_FluidConstants__desc__fields
};

#define CoffeeTemperature_CoffeeThermal_EnclosedConvection$enclosedConvection1_medium_ThermodynamicState__desc_added 1
const char* CoffeeTemperature_CoffeeThermal_EnclosedConvection$enclosedConvection1_medium_ThermodynamicState__desc__fields[5] = {"T","d","h","p","phase"};
struct record_description CoffeeTemperature_CoffeeThermal_EnclosedConvection$enclosedConvection1_medium_ThermodynamicState__desc = {
  "CoffeeTemperature_CoffeeThermal_EnclosedConvection$enclosedConvection1_medium_ThermodynamicState", /* package_record__X */
  "CoffeeTemperature.CoffeeThermal.EnclosedConvection$enclosedConvection1.medium.ThermodynamicState", /* package.record_X */
  CoffeeTemperature_CoffeeThermal_EnclosedConvection$enclosedConvection1_medium_ThermodynamicState__desc__fields
};

#define CoffeeTemperature_CoffeeThermal_NaturalConvection$naturalConvection1_medium_FluidConstants__desc_added 1
const char* CoffeeTemperature_CoffeeThermal_NaturalConvection$naturalConvection1_medium_FluidConstants__desc__fields[26] = {"HCRIT0","SCRIT0","acentricFactor","casRegistryNumber","chemicalFormula","criticalMolarVolume","criticalPressure","criticalTemperature","deltah","deltas","dipoleMoment","hasAccurateConductivityData","hasAccurateViscosityData","hasAcentricFactor","hasCriticalData","hasDipoleMoment","hasFundamentalEquation","hasIdealGasHeatCapacity","hasLiquidHeatCapacity","hasSolidHeatCapacity","hasVapourPressureCurve","iupacName","meltingPoint","molarMass","normalBoilingPoint","structureFormula"};
struct record_description CoffeeTemperature_CoffeeThermal_NaturalConvection$naturalConvection1_medium_FluidConstants__desc = {
  "CoffeeTemperature_CoffeeThermal_NaturalConvection$naturalConvection1_medium_FluidConstants", /* package_record__X */
  "CoffeeTemperature.CoffeeThermal.NaturalConvection$naturalConvection1.medium.FluidConstants", /* package.record_X */
  CoffeeTemperature_CoffeeThermal_NaturalConvection$naturalConvection1_medium_FluidConstants__desc__fields
};

#define CoffeeTemperature_CoffeeThermal_NaturalConvection$naturalConvection1_medium_ThermodynamicState__desc_added 1
const char* CoffeeTemperature_CoffeeThermal_NaturalConvection$naturalConvection1_medium_ThermodynamicState__desc__fields[2] = {"T","p"};
struct record_description CoffeeTemperature_CoffeeThermal_NaturalConvection$naturalConvection1_medium_ThermodynamicState__desc = {
  "CoffeeTemperature_CoffeeThermal_NaturalConvection$naturalConvection1_medium_ThermodynamicState", /* package_record__X */
  "CoffeeTemperature.CoffeeThermal.NaturalConvection$naturalConvection1.medium.ThermodynamicState", /* package.record_X */
  CoffeeTemperature_CoffeeThermal_NaturalConvection$naturalConvection1_medium_ThermodynamicState__desc__fields
};

#define Modelica_Fluid_Vessels_BaseClasses_VesselPortsData__desc_added 1
const char* Modelica_Fluid_Vessels_BaseClasses_VesselPortsData__desc__fields[4] = {"diameter","height","zeta_in","zeta_out"};
struct record_description Modelica_Fluid_Vessels_BaseClasses_VesselPortsData__desc = {
  "Modelica_Fluid_Vessels_BaseClasses_VesselPortsData", /* package_record__X */
  "Modelica.Fluid.Vessels.BaseClasses.VesselPortsData", /* package.record_X */
  Modelica_Fluid_Vessels_BaseClasses_VesselPortsData__desc__fields
};

#define Modelica_Fluid_Vessels_OpenTank$cup_Medium_SaturationProperties__desc_added 1
const char* Modelica_Fluid_Vessels_OpenTank$cup_Medium_SaturationProperties__desc__fields[2] = {"Tsat","psat"};
struct record_description Modelica_Fluid_Vessels_OpenTank$cup_Medium_SaturationProperties__desc = {
  "Modelica_Fluid_Vessels_OpenTank$cup_Medium_SaturationProperties", /* package_record__X */
  "Modelica.Fluid.Vessels.OpenTank$cup.Medium.SaturationProperties", /* package.record_X */
  Modelica_Fluid_Vessels_OpenTank$cup_Medium_SaturationProperties__desc__fields
};

#define Modelica_Media_Common_GibbsDerivs__desc_added 1
const char* Modelica_Media_Common_GibbsDerivs__desc__fields[11] = {"R","T","g","gpi","gpipi","gtau","gtaupi","gtautau","p","pi","tau"};
struct record_description Modelica_Media_Common_GibbsDerivs__desc = {
  "Modelica_Media_Common_GibbsDerivs", /* package_record__X */
  "Modelica.Media.Common.GibbsDerivs", /* package.record_X */
  Modelica_Media_Common_GibbsDerivs__desc__fields
};

#define Modelica_Media_Common_HelmholtzDerivs__desc_added 1
const char* Modelica_Media_Common_HelmholtzDerivs__desc__fields[11] = {"R","T","d","delta","f","fdelta","fdeltadelta","fdeltatau","ftau","ftautau","tau"};
struct record_description Modelica_Media_Common_HelmholtzDerivs__desc = {
  "Modelica_Media_Common_HelmholtzDerivs", /* package_record__X */
  "Modelica.Media.Common.HelmholtzDerivs", /* package.record_X */
  Modelica_Media_Common_HelmholtzDerivs__desc__fields
};

#define Modelica_Media_Common_NewtonDerivatives__pT__desc_added 1
const char* Modelica_Media_Common_NewtonDerivatives__pT__desc__fields[2] = {"p","pd"};
struct record_description Modelica_Media_Common_NewtonDerivatives__pT__desc = {
  "Modelica_Media_Common_NewtonDerivatives__pT", /* package_record__X */
  "Modelica.Media.Common.NewtonDerivatives_pT", /* package.record_X */
  Modelica_Media_Common_NewtonDerivatives__pT__desc__fields
};

#define Modelica_Media_Common_NewtonDerivatives__ph__desc_added 1
const char* Modelica_Media_Common_NewtonDerivatives__ph__desc__fields[6] = {"h","hd","ht","p","pd","pt"};
struct record_description Modelica_Media_Common_NewtonDerivatives__ph__desc = {
  "Modelica_Media_Common_NewtonDerivatives__ph", /* package_record__X */
  "Modelica.Media.Common.NewtonDerivatives_ph", /* package.record_X */
  Modelica_Media_Common_NewtonDerivatives__ph__desc__fields
};

#define Modelica_Media_Common_IF97BaseTwoPhase__desc_added 1
const char* Modelica_Media_Common_IF97BaseTwoPhase__desc__fields[16] = {"R","T","cp","cv","dpT","h","p","pd","phase","pt","region","rho","s","vp","vt","x"};
struct record_description Modelica_Media_Common_IF97BaseTwoPhase__desc = {
  "Modelica_Media_Common_IF97BaseTwoPhase", /* package_record__X */
  "Modelica.Media.Common.IF97BaseTwoPhase", /* package.record_X */
  Modelica_Media_Common_IF97BaseTwoPhase__desc__fields
};

#define Modelica_Media_Common_IF97PhaseBoundaryProperties__desc_added 1
const char* Modelica_Media_Common_IF97PhaseBoundaryProperties__desc__fields[13] = {"R","T","cp","cv","d","dpT","h","pd","pt","region3boundary","s","vp","vt"};
struct record_description Modelica_Media_Common_IF97PhaseBoundaryProperties__desc = {
  "Modelica_Media_Common_IF97PhaseBoundaryProperties", /* package_record__X */
  "Modelica.Media.Common.IF97PhaseBoundaryProperties", /* package.record_X */
  Modelica_Media_Common_IF97PhaseBoundaryProperties__desc__fields
};

#define Modelica_Media_Common_PhaseBoundaryProperties__desc_added 1
const char* Modelica_Media_Common_PhaseBoundaryProperties__desc__fields[8] = {"cp","cv","d","h","pd","pt","s","u"};
struct record_description Modelica_Media_Common_PhaseBoundaryProperties__desc = {
  "Modelica_Media_Common_PhaseBoundaryProperties", /* package_record__X */
  "Modelica.Media.Common.PhaseBoundaryProperties", /* package.record_X */
  Modelica_Media_Common_PhaseBoundaryProperties__desc__fields
};

#define Modelica_Media_IdealGases_Common_DataRecord__desc_added 1
const char* Modelica_Media_IdealGases_Common_DataRecord__desc__fields[10] = {"H0","Hf","MM","R","Tlimit","ahigh","alow","bhigh","blow","name"};
struct record_description Modelica_Media_IdealGases_Common_DataRecord__desc = {
  "Modelica_Media_IdealGases_Common_DataRecord", /* package_record__X */
  "Modelica.Media.IdealGases.Common.DataRecord", /* package.record_X */
  Modelica_Media_IdealGases_Common_DataRecord__desc__fields
};

#define Modelica_Fluid_Interfaces_FluidPort__a$pipe$port__a_Medium_FluidConstants__desc_added 1
const char* Modelica_Fluid_Interfaces_FluidPort__a$pipe$port__a_Medium_FluidConstants__desc__fields[28] = {"HCRIT0","SCRIT0","acentricFactor","casRegistryNumber","chemicalFormula","criticalMolarVolume","criticalPressure","criticalTemperature","deltah","deltas","dipoleMoment","hasAccurateConductivityData","hasAccurateViscosityData","hasAcentricFactor","hasCriticalData","hasDipoleMoment","hasFundamentalEquation","hasIdealGasHeatCapacity","hasLiquidHeatCapacity","hasSolidHeatCapacity","hasVapourPressureCurve","iupacName","meltingPoint","molarMass","normalBoilingPoint","structureFormula","triplePointPressure","triplePointTemperature"};
struct record_description Modelica_Fluid_Interfaces_FluidPort__a$pipe$port__a_Medium_FluidConstants__desc = {
  "Modelica_Fluid_Interfaces_FluidPort__a$pipe$port__a_Medium_FluidConstants", /* package_record__X */
  "Modelica.Fluid.Interfaces.FluidPort_a$pipe$port_a.Medium.FluidConstants", /* package.record_X */
  Modelica_Fluid_Interfaces_FluidPort__a$pipe$port__a_Medium_FluidConstants__desc__fields
};

#define Modelica_Fluid_Interfaces_FluidPort__a$valveIncompressible1$port__a_Medium_FluidConstants__desc_added 1
const char* Modelica_Fluid_Interfaces_FluidPort__a$valveIncompressible1$port__a_Medium_FluidConstants__desc__fields[28] = {"HCRIT0","SCRIT0","acentricFactor","casRegistryNumber","chemicalFormula","criticalMolarVolume","criticalPressure","criticalTemperature","deltah","deltas","dipoleMoment","hasAccurateConductivityData","hasAccurateViscosityData","hasAcentricFactor","hasCriticalData","hasDipoleMoment","hasFundamentalEquation","hasIdealGasHeatCapacity","hasLiquidHeatCapacity","hasSolidHeatCapacity","hasVapourPressureCurve","iupacName","meltingPoint","molarMass","normalBoilingPoint","structureFormula","triplePointPressure","triplePointTemperature"};
struct record_description Modelica_Fluid_Interfaces_FluidPort__a$valveIncompressible1$port__a_Medium_FluidConstants__desc = {
  "Modelica_Fluid_Interfaces_FluidPort__a$valveIncompressible1$port__a_Medium_FluidConstants", /* package_record__X */
  "Modelica.Fluid.Interfaces.FluidPort_a$valveIncompressible1$port_a.Medium.FluidConstants", /* package.record_X */
  Modelica_Fluid_Interfaces_FluidPort__a$valveIncompressible1$port__a_Medium_FluidConstants__desc__fields
};

#define Modelica_Fluid_Interfaces_FluidPort__b$pipe$port__b_Medium_FluidConstants__desc_added 1
const char* Modelica_Fluid_Interfaces_FluidPort__b$pipe$port__b_Medium_FluidConstants__desc__fields[28] = {"HCRIT0","SCRIT0","acentricFactor","casRegistryNumber","chemicalFormula","criticalMolarVolume","criticalPressure","criticalTemperature","deltah","deltas","dipoleMoment","hasAccurateConductivityData","hasAccurateViscosityData","hasAcentricFactor","hasCriticalData","hasDipoleMoment","hasFundamentalEquation","hasIdealGasHeatCapacity","hasLiquidHeatCapacity","hasSolidHeatCapacity","hasVapourPressureCurve","iupacName","meltingPoint","molarMass","normalBoilingPoint","structureFormula","triplePointPressure","triplePointTemperature"};
struct record_description Modelica_Fluid_Interfaces_FluidPort__b$pipe$port__b_Medium_FluidConstants__desc = {
  "Modelica_Fluid_Interfaces_FluidPort__b$pipe$port__b_Medium_FluidConstants", /* package_record__X */
  "Modelica.Fluid.Interfaces.FluidPort_b$pipe$port_b.Medium.FluidConstants", /* package.record_X */
  Modelica_Fluid_Interfaces_FluidPort__b$pipe$port__b_Medium_FluidConstants__desc__fields
};

#define Modelica_Fluid_Interfaces_FluidPort__b$valveIncompressible1$port__b_Medium_FluidConstants__desc_added 1
const char* Modelica_Fluid_Interfaces_FluidPort__b$valveIncompressible1$port__b_Medium_FluidConstants__desc__fields[28] = {"HCRIT0","SCRIT0","acentricFactor","casRegistryNumber","chemicalFormula","criticalMolarVolume","criticalPressure","criticalTemperature","deltah","deltas","dipoleMoment","hasAccurateConductivityData","hasAccurateViscosityData","hasAcentricFactor","hasCriticalData","hasDipoleMoment","hasFundamentalEquation","hasIdealGasHeatCapacity","hasLiquidHeatCapacity","hasSolidHeatCapacity","hasVapourPressureCurve","iupacName","meltingPoint","molarMass","normalBoilingPoint","structureFormula","triplePointPressure","triplePointTemperature"};
struct record_description Modelica_Fluid_Interfaces_FluidPort__b$valveIncompressible1$port__b_Medium_FluidConstants__desc = {
  "Modelica_Fluid_Interfaces_FluidPort__b$valveIncompressible1$port__b_Medium_FluidConstants", /* package_record__X */
  "Modelica.Fluid.Interfaces.FluidPort_b$valveIncompressible1$port_b.Medium.FluidConstants", /* package.record_X */
  Modelica_Fluid_Interfaces_FluidPort__b$valveIncompressible1$port__b_Medium_FluidConstants__desc__fields
};

#define Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_Medium_FluidConstants__desc_added 1
const char* Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_Medium_FluidConstants__desc__fields[28] = {"HCRIT0","SCRIT0","acentricFactor","casRegistryNumber","chemicalFormula","criticalMolarVolume","criticalPressure","criticalTemperature","deltah","deltas","dipoleMoment","hasAccurateConductivityData","hasAccurateViscosityData","hasAcentricFactor","hasCriticalData","hasDipoleMoment","hasFundamentalEquation","hasIdealGasHeatCapacity","hasLiquidHeatCapacity","hasSolidHeatCapacity","hasVapourPressureCurve","iupacName","meltingPoint","molarMass","normalBoilingPoint","structureFormula","triplePointPressure","triplePointTemperature"};
struct record_description Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_Medium_FluidConstants__desc = {
  "Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_Medium_FluidConstants", /* package_record__X */
  "Modelica.Fluid.Pipes.StaticPipe$pipe.FlowModel$pipe$flowModel.Medium.FluidConstants", /* package.record_X */
  Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_Medium_FluidConstants__desc__fields
};

#define Modelica_Fluid_Pipes_StaticPipe$pipe_Medium_FluidConstants__desc_added 1
const char* Modelica_Fluid_Pipes_StaticPipe$pipe_Medium_FluidConstants__desc__fields[28] = {"HCRIT0","SCRIT0","acentricFactor","casRegistryNumber","chemicalFormula","criticalMolarVolume","criticalPressure","criticalTemperature","deltah","deltas","dipoleMoment","hasAccurateConductivityData","hasAccurateViscosityData","hasAcentricFactor","hasCriticalData","hasDipoleMoment","hasFundamentalEquation","hasIdealGasHeatCapacity","hasLiquidHeatCapacity","hasSolidHeatCapacity","hasVapourPressureCurve","iupacName","meltingPoint","molarMass","normalBoilingPoint","structureFormula","triplePointPressure","triplePointTemperature"};
struct record_description Modelica_Fluid_Pipes_StaticPipe$pipe_Medium_FluidConstants__desc = {
  "Modelica_Fluid_Pipes_StaticPipe$pipe_Medium_FluidConstants", /* package_record__X */
  "Modelica.Fluid.Pipes.StaticPipe$pipe.Medium.FluidConstants", /* package.record_X */
  Modelica_Fluid_Pipes_StaticPipe$pipe_Medium_FluidConstants__desc__fields
};

#define Modelica_Fluid_Valves_ValveIncompressible$valveIncompressible1_Medium_FluidConstants__desc_added 1
const char* Modelica_Fluid_Valves_ValveIncompressible$valveIncompressible1_Medium_FluidConstants__desc__fields[28] = {"HCRIT0","SCRIT0","acentricFactor","casRegistryNumber","chemicalFormula","criticalMolarVolume","criticalPressure","criticalTemperature","deltah","deltas","dipoleMoment","hasAccurateConductivityData","hasAccurateViscosityData","hasAcentricFactor","hasCriticalData","hasDipoleMoment","hasFundamentalEquation","hasIdealGasHeatCapacity","hasLiquidHeatCapacity","hasSolidHeatCapacity","hasVapourPressureCurve","iupacName","meltingPoint","molarMass","normalBoilingPoint","structureFormula","triplePointPressure","triplePointTemperature"};
struct record_description Modelica_Fluid_Valves_ValveIncompressible$valveIncompressible1_Medium_FluidConstants__desc = {
  "Modelica_Fluid_Valves_ValveIncompressible$valveIncompressible1_Medium_FluidConstants", /* package_record__X */
  "Modelica.Fluid.Valves.ValveIncompressible$valveIncompressible1.Medium.FluidConstants", /* package.record_X */
  Modelica_Fluid_Valves_ValveIncompressible$valveIncompressible1_Medium_FluidConstants__desc__fields
};

#define Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$cup$ports_Medium_FluidConstants__desc_added 1
const char* Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$cup$ports_Medium_FluidConstants__desc__fields[28] = {"HCRIT0","SCRIT0","acentricFactor","casRegistryNumber","chemicalFormula","criticalMolarVolume","criticalPressure","criticalTemperature","deltah","deltas","dipoleMoment","hasAccurateConductivityData","hasAccurateViscosityData","hasAcentricFactor","hasCriticalData","hasDipoleMoment","hasFundamentalEquation","hasIdealGasHeatCapacity","hasLiquidHeatCapacity","hasSolidHeatCapacity","hasVapourPressureCurve","iupacName","meltingPoint","molarMass","normalBoilingPoint","structureFormula","triplePointPressure","triplePointTemperature"};
struct record_description Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$cup$ports_Medium_FluidConstants__desc = {
  "Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$cup$ports_Medium_FluidConstants", /* package_record__X */
  "Modelica.Fluid.Vessels.BaseClasses.VesselFluidPorts_b$cup$ports.Medium.FluidConstants", /* package.record_X */
  Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$cup$ports_Medium_FluidConstants__desc__fields
};

#define Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$yakan$ports_Medium_FluidConstants__desc_added 1
const char* Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$yakan$ports_Medium_FluidConstants__desc__fields[28] = {"HCRIT0","SCRIT0","acentricFactor","casRegistryNumber","chemicalFormula","criticalMolarVolume","criticalPressure","criticalTemperature","deltah","deltas","dipoleMoment","hasAccurateConductivityData","hasAccurateViscosityData","hasAcentricFactor","hasCriticalData","hasDipoleMoment","hasFundamentalEquation","hasIdealGasHeatCapacity","hasLiquidHeatCapacity","hasSolidHeatCapacity","hasVapourPressureCurve","iupacName","meltingPoint","molarMass","normalBoilingPoint","structureFormula","triplePointPressure","triplePointTemperature"};
struct record_description Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$yakan$ports_Medium_FluidConstants__desc = {
  "Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$yakan$ports_Medium_FluidConstants", /* package_record__X */
  "Modelica.Fluid.Vessels.BaseClasses.VesselFluidPorts_b$yakan$ports.Medium.FluidConstants", /* package.record_X */
  Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$yakan$ports_Medium_FluidConstants__desc__fields
};

#define Modelica_Fluid_Vessels_OpenTank$cup_HeatTransfer$cup$heatTransfer_Medium_FluidConstants__desc_added 1
const char* Modelica_Fluid_Vessels_OpenTank$cup_HeatTransfer$cup$heatTransfer_Medium_FluidConstants__desc__fields[28] = {"HCRIT0","SCRIT0","acentricFactor","casRegistryNumber","chemicalFormula","criticalMolarVolume","criticalPressure","criticalTemperature","deltah","deltas","dipoleMoment","hasAccurateConductivityData","hasAccurateViscosityData","hasAcentricFactor","hasCriticalData","hasDipoleMoment","hasFundamentalEquation","hasIdealGasHeatCapacity","hasLiquidHeatCapacity","hasSolidHeatCapacity","hasVapourPressureCurve","iupacName","meltingPoint","molarMass","normalBoilingPoint","structureFormula","triplePointPressure","triplePointTemperature"};
struct record_description Modelica_Fluid_Vessels_OpenTank$cup_HeatTransfer$cup$heatTransfer_Medium_FluidConstants__desc = {
  "Modelica_Fluid_Vessels_OpenTank$cup_HeatTransfer$cup$heatTransfer_Medium_FluidConstants", /* package_record__X */
  "Modelica.Fluid.Vessels.OpenTank$cup.HeatTransfer$cup$heatTransfer.Medium.FluidConstants", /* package.record_X */
  Modelica_Fluid_Vessels_OpenTank$cup_HeatTransfer$cup$heatTransfer_Medium_FluidConstants__desc__fields
};

#define Modelica_Fluid_Vessels_OpenTank$cup_Medium_FluidConstants__desc_added 1
const char* Modelica_Fluid_Vessels_OpenTank$cup_Medium_FluidConstants__desc__fields[28] = {"HCRIT0","SCRIT0","acentricFactor","casRegistryNumber","chemicalFormula","criticalMolarVolume","criticalPressure","criticalTemperature","deltah","deltas","dipoleMoment","hasAccurateConductivityData","hasAccurateViscosityData","hasAcentricFactor","hasCriticalData","hasDipoleMoment","hasFundamentalEquation","hasIdealGasHeatCapacity","hasLiquidHeatCapacity","hasSolidHeatCapacity","hasVapourPressureCurve","iupacName","meltingPoint","molarMass","normalBoilingPoint","structureFormula","triplePointPressure","triplePointTemperature"};
struct record_description Modelica_Fluid_Vessels_OpenTank$cup_Medium_FluidConstants__desc = {
  "Modelica_Fluid_Vessels_OpenTank$cup_Medium_FluidConstants", /* package_record__X */
  "Modelica.Fluid.Vessels.OpenTank$cup.Medium.FluidConstants", /* package.record_X */
  Modelica_Fluid_Vessels_OpenTank$cup_Medium_FluidConstants__desc__fields
};

#define Modelica_Fluid_Vessels_OpenTank$yakan_HeatTransfer$yakan$heatTransfer_Medium_FluidConstants__desc_added 1
const char* Modelica_Fluid_Vessels_OpenTank$yakan_HeatTransfer$yakan$heatTransfer_Medium_FluidConstants__desc__fields[28] = {"HCRIT0","SCRIT0","acentricFactor","casRegistryNumber","chemicalFormula","criticalMolarVolume","criticalPressure","criticalTemperature","deltah","deltas","dipoleMoment","hasAccurateConductivityData","hasAccurateViscosityData","hasAcentricFactor","hasCriticalData","hasDipoleMoment","hasFundamentalEquation","hasIdealGasHeatCapacity","hasLiquidHeatCapacity","hasSolidHeatCapacity","hasVapourPressureCurve","iupacName","meltingPoint","molarMass","normalBoilingPoint","structureFormula","triplePointPressure","triplePointTemperature"};
struct record_description Modelica_Fluid_Vessels_OpenTank$yakan_HeatTransfer$yakan$heatTransfer_Medium_FluidConstants__desc = {
  "Modelica_Fluid_Vessels_OpenTank$yakan_HeatTransfer$yakan$heatTransfer_Medium_FluidConstants", /* package_record__X */
  "Modelica.Fluid.Vessels.OpenTank$yakan.HeatTransfer$yakan$heatTransfer.Medium.FluidConstants", /* package.record_X */
  Modelica_Fluid_Vessels_OpenTank$yakan_HeatTransfer$yakan$heatTransfer_Medium_FluidConstants__desc__fields
};

#define Modelica_Fluid_Vessels_OpenTank$yakan_Medium_FluidConstants__desc_added 1
const char* Modelica_Fluid_Vessels_OpenTank$yakan_Medium_FluidConstants__desc__fields[28] = {"HCRIT0","SCRIT0","acentricFactor","casRegistryNumber","chemicalFormula","criticalMolarVolume","criticalPressure","criticalTemperature","deltah","deltas","dipoleMoment","hasAccurateConductivityData","hasAccurateViscosityData","hasAcentricFactor","hasCriticalData","hasDipoleMoment","hasFundamentalEquation","hasIdealGasHeatCapacity","hasLiquidHeatCapacity","hasSolidHeatCapacity","hasVapourPressureCurve","iupacName","meltingPoint","molarMass","normalBoilingPoint","structureFormula","triplePointPressure","triplePointTemperature"};
struct record_description Modelica_Fluid_Vessels_OpenTank$yakan_Medium_FluidConstants__desc = {
  "Modelica_Fluid_Vessels_OpenTank$yakan_Medium_FluidConstants", /* package_record__X */
  "Modelica.Fluid.Vessels.OpenTank$yakan.Medium.FluidConstants", /* package.record_X */
  Modelica_Fluid_Vessels_OpenTank$yakan_Medium_FluidConstants__desc__fields
};

#define Modelica_Media_Interfaces_Types_TwoPhase_FluidConstants__desc_added 1
const char* Modelica_Media_Interfaces_Types_TwoPhase_FluidConstants__desc__fields[28] = {"HCRIT0","SCRIT0","acentricFactor","casRegistryNumber","chemicalFormula","criticalMolarVolume","criticalPressure","criticalTemperature","deltah","deltas","dipoleMoment","hasAccurateConductivityData","hasAccurateViscosityData","hasAcentricFactor","hasCriticalData","hasDipoleMoment","hasFundamentalEquation","hasIdealGasHeatCapacity","hasLiquidHeatCapacity","hasSolidHeatCapacity","hasVapourPressureCurve","iupacName","meltingPoint","molarMass","normalBoilingPoint","structureFormula","triplePointPressure","triplePointTemperature"};
struct record_description Modelica_Media_Interfaces_Types_TwoPhase_FluidConstants__desc = {
  "Modelica_Media_Interfaces_Types_TwoPhase_FluidConstants", /* package_record__X */
  "Modelica.Media.Interfaces.Types.TwoPhase.FluidConstants", /* package.record_X */
  Modelica_Media_Interfaces_Types_TwoPhase_FluidConstants__desc__fields
};

#define Modelica_Media_Interfaces_Types_TwoPhase_FluidConstants$waterConstants__desc_added 1
const char* Modelica_Media_Interfaces_Types_TwoPhase_FluidConstants$waterConstants__desc__fields[28] = {"HCRIT0","SCRIT0","acentricFactor","casRegistryNumber","chemicalFormula","criticalMolarVolume","criticalPressure","criticalTemperature","deltah","deltas","dipoleMoment","hasAccurateConductivityData","hasAccurateViscosityData","hasAcentricFactor","hasCriticalData","hasDipoleMoment","hasFundamentalEquation","hasIdealGasHeatCapacity","hasLiquidHeatCapacity","hasSolidHeatCapacity","hasVapourPressureCurve","iupacName","meltingPoint","molarMass","normalBoilingPoint","structureFormula","triplePointPressure","triplePointTemperature"};
struct record_description Modelica_Media_Interfaces_Types_TwoPhase_FluidConstants$waterConstants__desc = {
  "Modelica_Media_Interfaces_Types_TwoPhase_FluidConstants$waterConstants", /* package_record__X */
  "Modelica.Media.Interfaces.Types.TwoPhase.FluidConstants$waterConstants", /* package.record_X */
  Modelica_Media_Interfaces_Types_TwoPhase_FluidConstants$waterConstants__desc__fields
};

#define Modelica_Fluid_Interfaces_FluidPort__a$pipe$port__a_Medium_ThermodynamicState__desc_added 1
const char* Modelica_Fluid_Interfaces_FluidPort__a$pipe$port__a_Medium_ThermodynamicState__desc__fields[5] = {"T","d","h","p","phase"};
struct record_description Modelica_Fluid_Interfaces_FluidPort__a$pipe$port__a_Medium_ThermodynamicState__desc = {
  "Modelica_Fluid_Interfaces_FluidPort__a$pipe$port__a_Medium_ThermodynamicState", /* package_record__X */
  "Modelica.Fluid.Interfaces.FluidPort_a$pipe$port_a.Medium.ThermodynamicState", /* package.record_X */
  Modelica_Fluid_Interfaces_FluidPort__a$pipe$port__a_Medium_ThermodynamicState__desc__fields
};

#define Modelica_Fluid_Interfaces_FluidPort__a$valveIncompressible1$port__a_Medium_ThermodynamicState__desc_added 1
const char* Modelica_Fluid_Interfaces_FluidPort__a$valveIncompressible1$port__a_Medium_ThermodynamicState__desc__fields[5] = {"T","d","h","p","phase"};
struct record_description Modelica_Fluid_Interfaces_FluidPort__a$valveIncompressible1$port__a_Medium_ThermodynamicState__desc = {
  "Modelica_Fluid_Interfaces_FluidPort__a$valveIncompressible1$port__a_Medium_ThermodynamicState", /* package_record__X */
  "Modelica.Fluid.Interfaces.FluidPort_a$valveIncompressible1$port_a.Medium.ThermodynamicState", /* package.record_X */
  Modelica_Fluid_Interfaces_FluidPort__a$valveIncompressible1$port__a_Medium_ThermodynamicState__desc__fields
};

#define Modelica_Fluid_Interfaces_FluidPort__b$pipe$port__b_Medium_ThermodynamicState__desc_added 1
const char* Modelica_Fluid_Interfaces_FluidPort__b$pipe$port__b_Medium_ThermodynamicState__desc__fields[5] = {"T","d","h","p","phase"};
struct record_description Modelica_Fluid_Interfaces_FluidPort__b$pipe$port__b_Medium_ThermodynamicState__desc = {
  "Modelica_Fluid_Interfaces_FluidPort__b$pipe$port__b_Medium_ThermodynamicState", /* package_record__X */
  "Modelica.Fluid.Interfaces.FluidPort_b$pipe$port_b.Medium.ThermodynamicState", /* package.record_X */
  Modelica_Fluid_Interfaces_FluidPort__b$pipe$port__b_Medium_ThermodynamicState__desc__fields
};

#define Modelica_Fluid_Interfaces_FluidPort__b$valveIncompressible1$port__b_Medium_ThermodynamicState__desc_added 1
const char* Modelica_Fluid_Interfaces_FluidPort__b$valveIncompressible1$port__b_Medium_ThermodynamicState__desc__fields[5] = {"T","d","h","p","phase"};
struct record_description Modelica_Fluid_Interfaces_FluidPort__b$valveIncompressible1$port__b_Medium_ThermodynamicState__desc = {
  "Modelica_Fluid_Interfaces_FluidPort__b$valveIncompressible1$port__b_Medium_ThermodynamicState", /* package_record__X */
  "Modelica.Fluid.Interfaces.FluidPort_b$valveIncompressible1$port_b.Medium.ThermodynamicState", /* package.record_X */
  Modelica_Fluid_Interfaces_FluidPort__b$valveIncompressible1$port__b_Medium_ThermodynamicState__desc__fields
};

#define Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_Medium_ThermodynamicState__desc_added 1
const char* Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_Medium_ThermodynamicState__desc__fields[5] = {"T","d","h","p","phase"};
struct record_description Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_Medium_ThermodynamicState__desc = {
  "Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_Medium_ThermodynamicState", /* package_record__X */
  "Modelica.Fluid.Pipes.StaticPipe$pipe.FlowModel$pipe$flowModel.Medium.ThermodynamicState", /* package.record_X */
  Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_Medium_ThermodynamicState__desc__fields
};

#define Modelica_Fluid_Pipes_StaticPipe$pipe_Medium_ThermodynamicState__desc_added 1
const char* Modelica_Fluid_Pipes_StaticPipe$pipe_Medium_ThermodynamicState__desc__fields[5] = {"T","d","h","p","phase"};
struct record_description Modelica_Fluid_Pipes_StaticPipe$pipe_Medium_ThermodynamicState__desc = {
  "Modelica_Fluid_Pipes_StaticPipe$pipe_Medium_ThermodynamicState", /* package_record__X */
  "Modelica.Fluid.Pipes.StaticPipe$pipe.Medium.ThermodynamicState", /* package.record_X */
  Modelica_Fluid_Pipes_StaticPipe$pipe_Medium_ThermodynamicState__desc__fields
};

#define Modelica_Fluid_Valves_ValveIncompressible$valveIncompressible1_Medium_ThermodynamicState__desc_added 1
const char* Modelica_Fluid_Valves_ValveIncompressible$valveIncompressible1_Medium_ThermodynamicState__desc__fields[5] = {"T","d","h","p","phase"};
struct record_description Modelica_Fluid_Valves_ValveIncompressible$valveIncompressible1_Medium_ThermodynamicState__desc = {
  "Modelica_Fluid_Valves_ValveIncompressible$valveIncompressible1_Medium_ThermodynamicState", /* package_record__X */
  "Modelica.Fluid.Valves.ValveIncompressible$valveIncompressible1.Medium.ThermodynamicState", /* package.record_X */
  Modelica_Fluid_Valves_ValveIncompressible$valveIncompressible1_Medium_ThermodynamicState__desc__fields
};

#define Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$cup$ports_Medium_ThermodynamicState__desc_added 1
const char* Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$cup$ports_Medium_ThermodynamicState__desc__fields[5] = {"T","d","h","p","phase"};
struct record_description Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$cup$ports_Medium_ThermodynamicState__desc = {
  "Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$cup$ports_Medium_ThermodynamicState", /* package_record__X */
  "Modelica.Fluid.Vessels.BaseClasses.VesselFluidPorts_b$cup$ports.Medium.ThermodynamicState", /* package.record_X */
  Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$cup$ports_Medium_ThermodynamicState__desc__fields
};

#define Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$yakan$ports_Medium_ThermodynamicState__desc_added 1
const char* Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$yakan$ports_Medium_ThermodynamicState__desc__fields[5] = {"T","d","h","p","phase"};
struct record_description Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$yakan$ports_Medium_ThermodynamicState__desc = {
  "Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$yakan$ports_Medium_ThermodynamicState", /* package_record__X */
  "Modelica.Fluid.Vessels.BaseClasses.VesselFluidPorts_b$yakan$ports.Medium.ThermodynamicState", /* package.record_X */
  Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$yakan$ports_Medium_ThermodynamicState__desc__fields
};

#define Modelica_Fluid_Vessels_OpenTank$cup_HeatTransfer$cup$heatTransfer_Medium_ThermodynamicState__desc_added 1
const char* Modelica_Fluid_Vessels_OpenTank$cup_HeatTransfer$cup$heatTransfer_Medium_ThermodynamicState__desc__fields[5] = {"T","d","h","p","phase"};
struct record_description Modelica_Fluid_Vessels_OpenTank$cup_HeatTransfer$cup$heatTransfer_Medium_ThermodynamicState__desc = {
  "Modelica_Fluid_Vessels_OpenTank$cup_HeatTransfer$cup$heatTransfer_Medium_ThermodynamicState", /* package_record__X */
  "Modelica.Fluid.Vessels.OpenTank$cup.HeatTransfer$cup$heatTransfer.Medium.ThermodynamicState", /* package.record_X */
  Modelica_Fluid_Vessels_OpenTank$cup_HeatTransfer$cup$heatTransfer_Medium_ThermodynamicState__desc__fields
};

#define Modelica_Fluid_Vessels_OpenTank$cup_Medium_ThermodynamicState__desc_added 1
const char* Modelica_Fluid_Vessels_OpenTank$cup_Medium_ThermodynamicState__desc__fields[5] = {"T","d","h","p","phase"};
struct record_description Modelica_Fluid_Vessels_OpenTank$cup_Medium_ThermodynamicState__desc = {
  "Modelica_Fluid_Vessels_OpenTank$cup_Medium_ThermodynamicState", /* package_record__X */
  "Modelica.Fluid.Vessels.OpenTank$cup.Medium.ThermodynamicState", /* package.record_X */
  Modelica_Fluid_Vessels_OpenTank$cup_Medium_ThermodynamicState__desc__fields
};

#define Modelica_Fluid_Vessels_OpenTank$yakan_HeatTransfer$yakan$heatTransfer_Medium_ThermodynamicState__desc_added 1
const char* Modelica_Fluid_Vessels_OpenTank$yakan_HeatTransfer$yakan$heatTransfer_Medium_ThermodynamicState__desc__fields[5] = {"T","d","h","p","phase"};
struct record_description Modelica_Fluid_Vessels_OpenTank$yakan_HeatTransfer$yakan$heatTransfer_Medium_ThermodynamicState__desc = {
  "Modelica_Fluid_Vessels_OpenTank$yakan_HeatTransfer$yakan$heatTransfer_Medium_ThermodynamicState", /* package_record__X */
  "Modelica.Fluid.Vessels.OpenTank$yakan.HeatTransfer$yakan$heatTransfer.Medium.ThermodynamicState", /* package.record_X */
  Modelica_Fluid_Vessels_OpenTank$yakan_HeatTransfer$yakan$heatTransfer_Medium_ThermodynamicState__desc__fields
};

#define Modelica_Fluid_Vessels_OpenTank$yakan_Medium_ThermodynamicState__desc_added 1
const char* Modelica_Fluid_Vessels_OpenTank$yakan_Medium_ThermodynamicState__desc__fields[5] = {"T","d","h","p","phase"};
struct record_description Modelica_Fluid_Vessels_OpenTank$yakan_Medium_ThermodynamicState__desc = {
  "Modelica_Fluid_Vessels_OpenTank$yakan_Medium_ThermodynamicState", /* package_record__X */
  "Modelica.Fluid.Vessels.OpenTank$yakan.Medium.ThermodynamicState", /* package.record_X */
  Modelica_Fluid_Vessels_OpenTank$yakan_Medium_ThermodynamicState__desc__fields
};

#define CoffeeTemperature_CoffeeThermal_NaturalConvection$naturalConvection21_medium_FluidConstants__desc_added 1
const char* CoffeeTemperature_CoffeeThermal_NaturalConvection$naturalConvection21_medium_FluidConstants__desc__fields[26] = {"HCRIT0","SCRIT0","acentricFactor","casRegistryNumber","chemicalFormula","criticalMolarVolume","criticalPressure","criticalTemperature","deltah","deltas","dipoleMoment","hasAccurateConductivityData","hasAccurateViscosityData","hasAcentricFactor","hasCriticalData","hasDipoleMoment","hasFundamentalEquation","hasIdealGasHeatCapacity","hasLiquidHeatCapacity","hasSolidHeatCapacity","hasVapourPressureCurve","iupacName","meltingPoint","molarMass","normalBoilingPoint","structureFormula"};
struct record_description CoffeeTemperature_CoffeeThermal_NaturalConvection$naturalConvection21_medium_FluidConstants__desc = {
  "CoffeeTemperature_CoffeeThermal_NaturalConvection$naturalConvection21_medium_FluidConstants", /* package_record__X */
  "CoffeeTemperature.CoffeeThermal.NaturalConvection$naturalConvection21.medium.FluidConstants", /* package.record_X */
  CoffeeTemperature_CoffeeThermal_NaturalConvection$naturalConvection21_medium_FluidConstants__desc__fields
};

#define Modelica_Media_Interfaces_Types_IdealGas_FluidConstants__desc_added 1
const char* Modelica_Media_Interfaces_Types_IdealGas_FluidConstants__desc__fields[26] = {"HCRIT0","SCRIT0","acentricFactor","casRegistryNumber","chemicalFormula","criticalMolarVolume","criticalPressure","criticalTemperature","deltah","deltas","dipoleMoment","hasAccurateConductivityData","hasAccurateViscosityData","hasAcentricFactor","hasCriticalData","hasDipoleMoment","hasFundamentalEquation","hasIdealGasHeatCapacity","hasLiquidHeatCapacity","hasSolidHeatCapacity","hasVapourPressureCurve","iupacName","meltingPoint","molarMass","normalBoilingPoint","structureFormula"};
struct record_description Modelica_Media_Interfaces_Types_IdealGas_FluidConstants__desc = {
  "Modelica_Media_Interfaces_Types_IdealGas_FluidConstants", /* package_record__X */
  "Modelica.Media.Interfaces.Types.IdealGas.FluidConstants", /* package.record_X */
  Modelica_Media_Interfaces_Types_IdealGas_FluidConstants__desc__fields
};

#define Modelica_Media_Interfaces_Types_IdealGas_FluidConstants$N2__desc_added 1
const char* Modelica_Media_Interfaces_Types_IdealGas_FluidConstants$N2__desc__fields[26] = {"HCRIT0","SCRIT0","acentricFactor","casRegistryNumber","chemicalFormula","criticalMolarVolume","criticalPressure","criticalTemperature","deltah","deltas","dipoleMoment","hasAccurateConductivityData","hasAccurateViscosityData","hasAcentricFactor","hasCriticalData","hasDipoleMoment","hasFundamentalEquation","hasIdealGasHeatCapacity","hasLiquidHeatCapacity","hasSolidHeatCapacity","hasVapourPressureCurve","iupacName","meltingPoint","molarMass","normalBoilingPoint","structureFormula"};
struct record_description Modelica_Media_Interfaces_Types_IdealGas_FluidConstants$N2__desc = {
  "Modelica_Media_Interfaces_Types_IdealGas_FluidConstants$N2", /* package_record__X */
  "Modelica.Media.Interfaces.Types.IdealGas.FluidConstants$N2", /* package.record_X */
  Modelica_Media_Interfaces_Types_IdealGas_FluidConstants$N2__desc__fields
};

#define CoffeeTemperature_CoffeeThermal_NaturalConvection$naturalConvection21_medium_ThermodynamicState__desc_added 1
const char* CoffeeTemperature_CoffeeThermal_NaturalConvection$naturalConvection21_medium_ThermodynamicState__desc__fields[2] = {"T","p"};
struct record_description CoffeeTemperature_CoffeeThermal_NaturalConvection$naturalConvection21_medium_ThermodynamicState__desc = {
  "CoffeeTemperature_CoffeeThermal_NaturalConvection$naturalConvection21_medium_ThermodynamicState", /* package_record__X */
  "CoffeeTemperature.CoffeeThermal.NaturalConvection$naturalConvection21.medium.ThermodynamicState", /* package.record_X */
  CoffeeTemperature_CoffeeThermal_NaturalConvection$naturalConvection21_medium_ThermodynamicState__desc__fields
};

#define Modelica_Media_Incompressible_TableBased_ThermodynamicState__desc_added 1
const char* Modelica_Media_Incompressible_TableBased_ThermodynamicState__desc__fields[2] = {"T","p"};
struct record_description Modelica_Media_Incompressible_TableBased_ThermodynamicState__desc = {
  "Modelica_Media_Incompressible_TableBased_ThermodynamicState", /* package_record__X */
  "Modelica.Media.Incompressible.TableBased.ThermodynamicState", /* package.record_X */
  Modelica_Media_Incompressible_TableBased_ThermodynamicState__desc__fields
};

#define Modelica_Fluid_Vessels_OpenTank$yakan_Medium_SaturationProperties__desc_added 1
const char* Modelica_Fluid_Vessels_OpenTank$yakan_Medium_SaturationProperties__desc__fields[2] = {"Tsat","psat"};
struct record_description Modelica_Fluid_Vessels_OpenTank$yakan_Medium_SaturationProperties__desc = {
  "Modelica_Fluid_Vessels_OpenTank$yakan_Medium_SaturationProperties", /* package_record__X */
  "Modelica.Fluid.Vessels.OpenTank$yakan.Medium.SaturationProperties", /* package.record_X */
  Modelica_Fluid_Vessels_OpenTank$yakan_Medium_SaturationProperties__desc__fields
};

#define Modelica_Media_IdealGases_Common_DataRecord$Air__desc_added 1
const char* Modelica_Media_IdealGases_Common_DataRecord$Air__desc__fields[10] = {"H0","Hf","MM","R","Tlimit","ahigh","alow","bhigh","blow","name"};
struct record_description Modelica_Media_IdealGases_Common_DataRecord$Air__desc = {
  "Modelica_Media_IdealGases_Common_DataRecord$Air", /* package_record__X */
  "Modelica.Media.IdealGases.Common.DataRecord$Air", /* package.record_X */
  Modelica_Media_IdealGases_Common_DataRecord$Air__desc__fields
};

#define Modelica_Media_IdealGases_Common_DataRecord$Ar__desc_added 1
const char* Modelica_Media_IdealGases_Common_DataRecord$Ar__desc__fields[10] = {"H0","Hf","MM","R","Tlimit","ahigh","alow","bhigh","blow","name"};
struct record_description Modelica_Media_IdealGases_Common_DataRecord$Ar__desc = {
  "Modelica_Media_IdealGases_Common_DataRecord$Ar", /* package_record__X */
  "Modelica.Media.IdealGases.Common.DataRecord$Ar", /* package.record_X */
  Modelica_Media_IdealGases_Common_DataRecord$Ar__desc__fields
};

#define Modelica_Media_IdealGases_Common_DataRecord$C2H2__vinylidene__desc_added 1
const char* Modelica_Media_IdealGases_Common_DataRecord$C2H2__vinylidene__desc__fields[10] = {"H0","Hf","MM","R","Tlimit","ahigh","alow","bhigh","blow","name"};
struct record_description Modelica_Media_IdealGases_Common_DataRecord$C2H2__vinylidene__desc = {
  "Modelica_Media_IdealGases_Common_DataRecord$C2H2__vinylidene", /* package_record__X */
  "Modelica.Media.IdealGases.Common.DataRecord$C2H2_vinylidene", /* package.record_X */
  Modelica_Media_IdealGases_Common_DataRecord$C2H2__vinylidene__desc__fields
};

#define Modelica_Media_IdealGases_Common_DataRecord$C2H4__desc_added 1
const char* Modelica_Media_IdealGases_Common_DataRecord$C2H4__desc__fields[10] = {"H0","Hf","MM","R","Tlimit","ahigh","alow","bhigh","blow","name"};
struct record_description Modelica_Media_IdealGases_Common_DataRecord$C2H4__desc = {
  "Modelica_Media_IdealGases_Common_DataRecord$C2H4", /* package_record__X */
  "Modelica.Media.IdealGases.Common.DataRecord$C2H4", /* package.record_X */
  Modelica_Media_IdealGases_Common_DataRecord$C2H4__desc__fields
};

#define Modelica_Media_IdealGases_Common_DataRecord$C2H5OH__desc_added 1
const char* Modelica_Media_IdealGases_Common_DataRecord$C2H5OH__desc__fields[10] = {"H0","Hf","MM","R","Tlimit","ahigh","alow","bhigh","blow","name"};
struct record_description Modelica_Media_IdealGases_Common_DataRecord$C2H5OH__desc = {
  "Modelica_Media_IdealGases_Common_DataRecord$C2H5OH", /* package_record__X */
  "Modelica.Media.IdealGases.Common.DataRecord$C2H5OH", /* package.record_X */
  Modelica_Media_IdealGases_Common_DataRecord$C2H5OH__desc__fields
};

#define Modelica_Media_IdealGases_Common_DataRecord$C2H6__desc_added 1
const char* Modelica_Media_IdealGases_Common_DataRecord$C2H6__desc__fields[10] = {"H0","Hf","MM","R","Tlimit","ahigh","alow","bhigh","blow","name"};
struct record_description Modelica_Media_IdealGases_Common_DataRecord$C2H6__desc = {
  "Modelica_Media_IdealGases_Common_DataRecord$C2H6", /* package_record__X */
  "Modelica.Media.IdealGases.Common.DataRecord$C2H6", /* package.record_X */
  Modelica_Media_IdealGases_Common_DataRecord$C2H6__desc__fields
};

#define Modelica_Media_IdealGases_Common_DataRecord$C3H6__propylene__desc_added 1
const char* Modelica_Media_IdealGases_Common_DataRecord$C3H6__propylene__desc__fields[10] = {"H0","Hf","MM","R","Tlimit","ahigh","alow","bhigh","blow","name"};
struct record_description Modelica_Media_IdealGases_Common_DataRecord$C3H6__propylene__desc = {
  "Modelica_Media_IdealGases_Common_DataRecord$C3H6__propylene", /* package_record__X */
  "Modelica.Media.IdealGases.Common.DataRecord$C3H6_propylene", /* package.record_X */
  Modelica_Media_IdealGases_Common_DataRecord$C3H6__propylene__desc__fields
};

#define Modelica_Media_IdealGases_Common_DataRecord$C3H8__desc_added 1
const char* Modelica_Media_IdealGases_Common_DataRecord$C3H8__desc__fields[10] = {"H0","Hf","MM","R","Tlimit","ahigh","alow","bhigh","blow","name"};
struct record_description Modelica_Media_IdealGases_Common_DataRecord$C3H8__desc = {
  "Modelica_Media_IdealGases_Common_DataRecord$C3H8", /* package_record__X */
  "Modelica.Media.IdealGases.Common.DataRecord$C3H8", /* package.record_X */
  Modelica_Media_IdealGases_Common_DataRecord$C3H8__desc__fields
};

#define Modelica_Media_IdealGases_Common_DataRecord$C4H10__n__butane__desc_added 1
const char* Modelica_Media_IdealGases_Common_DataRecord$C4H10__n__butane__desc__fields[10] = {"H0","Hf","MM","R","Tlimit","ahigh","alow","bhigh","blow","name"};
struct record_description Modelica_Media_IdealGases_Common_DataRecord$C4H10__n__butane__desc = {
  "Modelica_Media_IdealGases_Common_DataRecord$C4H10__n__butane", /* package_record__X */
  "Modelica.Media.IdealGases.Common.DataRecord$C4H10_n_butane", /* package.record_X */
  Modelica_Media_IdealGases_Common_DataRecord$C4H10__n__butane__desc__fields
};

#define Modelica_Media_IdealGases_Common_DataRecord$C4H8__1__butene__desc_added 1
const char* Modelica_Media_IdealGases_Common_DataRecord$C4H8__1__butene__desc__fields[10] = {"H0","Hf","MM","R","Tlimit","ahigh","alow","bhigh","blow","name"};
struct record_description Modelica_Media_IdealGases_Common_DataRecord$C4H8__1__butene__desc = {
  "Modelica_Media_IdealGases_Common_DataRecord$C4H8__1__butene", /* package_record__X */
  "Modelica.Media.IdealGases.Common.DataRecord$C4H8_1_butene", /* package.record_X */
  Modelica_Media_IdealGases_Common_DataRecord$C4H8__1__butene__desc__fields
};

#define Modelica_Media_IdealGases_Common_DataRecord$C5H10__1__pentene__desc_added 1
const char* Modelica_Media_IdealGases_Common_DataRecord$C5H10__1__pentene__desc__fields[10] = {"H0","Hf","MM","R","Tlimit","ahigh","alow","bhigh","blow","name"};
struct record_description Modelica_Media_IdealGases_Common_DataRecord$C5H10__1__pentene__desc = {
  "Modelica_Media_IdealGases_Common_DataRecord$C5H10__1__pentene", /* package_record__X */
  "Modelica.Media.IdealGases.Common.DataRecord$C5H10_1_pentene", /* package.record_X */
  Modelica_Media_IdealGases_Common_DataRecord$C5H10__1__pentene__desc__fields
};

#define Modelica_Media_IdealGases_Common_DataRecord$C5H12__n__pentane__desc_added 1
const char* Modelica_Media_IdealGases_Common_DataRecord$C5H12__n__pentane__desc__fields[10] = {"H0","Hf","MM","R","Tlimit","ahigh","alow","bhigh","blow","name"};
struct record_description Modelica_Media_IdealGases_Common_DataRecord$C5H12__n__pentane__desc = {
  "Modelica_Media_IdealGases_Common_DataRecord$C5H12__n__pentane", /* package_record__X */
  "Modelica.Media.IdealGases.Common.DataRecord$C5H12_n_pentane", /* package.record_X */
  Modelica_Media_IdealGases_Common_DataRecord$C5H12__n__pentane__desc__fields
};

#define Modelica_Media_IdealGases_Common_DataRecord$C6H12__1__hexene__desc_added 1
const char* Modelica_Media_IdealGases_Common_DataRecord$C6H12__1__hexene__desc__fields[10] = {"H0","Hf","MM","R","Tlimit","ahigh","alow","bhigh","blow","name"};
struct record_description Modelica_Media_IdealGases_Common_DataRecord$C6H12__1__hexene__desc = {
  "Modelica_Media_IdealGases_Common_DataRecord$C6H12__1__hexene", /* package_record__X */
  "Modelica.Media.IdealGases.Common.DataRecord$C6H12_1_hexene", /* package.record_X */
  Modelica_Media_IdealGases_Common_DataRecord$C6H12__1__hexene__desc__fields
};

#define Modelica_Media_IdealGases_Common_DataRecord$C6H14__n__hexane__desc_added 1
const char* Modelica_Media_IdealGases_Common_DataRecord$C6H14__n__hexane__desc__fields[10] = {"H0","Hf","MM","R","Tlimit","ahigh","alow","bhigh","blow","name"};
struct record_description Modelica_Media_IdealGases_Common_DataRecord$C6H14__n__hexane__desc = {
  "Modelica_Media_IdealGases_Common_DataRecord$C6H14__n__hexane", /* package_record__X */
  "Modelica.Media.IdealGases.Common.DataRecord$C6H14_n_hexane", /* package.record_X */
  Modelica_Media_IdealGases_Common_DataRecord$C6H14__n__hexane__desc__fields
};

#define Modelica_Media_IdealGases_Common_DataRecord$C6H6__desc_added 1
const char* Modelica_Media_IdealGases_Common_DataRecord$C6H6__desc__fields[10] = {"H0","Hf","MM","R","Tlimit","ahigh","alow","bhigh","blow","name"};
struct record_description Modelica_Media_IdealGases_Common_DataRecord$C6H6__desc = {
  "Modelica_Media_IdealGases_Common_DataRecord$C6H6", /* package_record__X */
  "Modelica.Media.IdealGases.Common.DataRecord$C6H6", /* package.record_X */
  Modelica_Media_IdealGases_Common_DataRecord$C6H6__desc__fields
};

#define Modelica_Media_IdealGases_Common_DataRecord$C7H14__1__heptene__desc_added 1
const char* Modelica_Media_IdealGases_Common_DataRecord$C7H14__1__heptene__desc__fields[10] = {"H0","Hf","MM","R","Tlimit","ahigh","alow","bhigh","blow","name"};
struct record_description Modelica_Media_IdealGases_Common_DataRecord$C7H14__1__heptene__desc = {
  "Modelica_Media_IdealGases_Common_DataRecord$C7H14__1__heptene", /* package_record__X */
  "Modelica.Media.IdealGases.Common.DataRecord$C7H14_1_heptene", /* package.record_X */
  Modelica_Media_IdealGases_Common_DataRecord$C7H14__1__heptene__desc__fields
};

#define Modelica_Media_IdealGases_Common_DataRecord$C7H16__n__heptane__desc_added 1
const char* Modelica_Media_IdealGases_Common_DataRecord$C7H16__n__heptane__desc__fields[10] = {"H0","Hf","MM","R","Tlimit","ahigh","alow","bhigh","blow","name"};
struct record_description Modelica_Media_IdealGases_Common_DataRecord$C7H16__n__heptane__desc = {
  "Modelica_Media_IdealGases_Common_DataRecord$C7H16__n__heptane", /* package_record__X */
  "Modelica.Media.IdealGases.Common.DataRecord$C7H16_n_heptane", /* package.record_X */
  Modelica_Media_IdealGases_Common_DataRecord$C7H16__n__heptane__desc__fields
};

#define Modelica_Media_IdealGases_Common_DataRecord$C8H10__ethylbenz__desc_added 1
const char* Modelica_Media_IdealGases_Common_DataRecord$C8H10__ethylbenz__desc__fields[10] = {"H0","Hf","MM","R","Tlimit","ahigh","alow","bhigh","blow","name"};
struct record_description Modelica_Media_IdealGases_Common_DataRecord$C8H10__ethylbenz__desc = {
  "Modelica_Media_IdealGases_Common_DataRecord$C8H10__ethylbenz", /* package_record__X */
  "Modelica.Media.IdealGases.Common.DataRecord$C8H10_ethylbenz", /* package.record_X */
  Modelica_Media_IdealGases_Common_DataRecord$C8H10__ethylbenz__desc__fields
};

#define Modelica_Media_IdealGases_Common_DataRecord$C8H18__n__octane__desc_added 1
const char* Modelica_Media_IdealGases_Common_DataRecord$C8H18__n__octane__desc__fields[10] = {"H0","Hf","MM","R","Tlimit","ahigh","alow","bhigh","blow","name"};
struct record_description Modelica_Media_IdealGases_Common_DataRecord$C8H18__n__octane__desc = {
  "Modelica_Media_IdealGases_Common_DataRecord$C8H18__n__octane", /* package_record__X */
  "Modelica.Media.IdealGases.Common.DataRecord$C8H18_n_octane", /* package.record_X */
  Modelica_Media_IdealGases_Common_DataRecord$C8H18__n__octane__desc__fields
};

#define Modelica_Media_IdealGases_Common_DataRecord$CH3OH__desc_added 1
const char* Modelica_Media_IdealGases_Common_DataRecord$CH3OH__desc__fields[10] = {"H0","Hf","MM","R","Tlimit","ahigh","alow","bhigh","blow","name"};
struct record_description Modelica_Media_IdealGases_Common_DataRecord$CH3OH__desc = {
  "Modelica_Media_IdealGases_Common_DataRecord$CH3OH", /* package_record__X */
  "Modelica.Media.IdealGases.Common.DataRecord$CH3OH", /* package.record_X */
  Modelica_Media_IdealGases_Common_DataRecord$CH3OH__desc__fields
};

#define Modelica_Media_IdealGases_Common_DataRecord$CH4__desc_added 1
const char* Modelica_Media_IdealGases_Common_DataRecord$CH4__desc__fields[10] = {"H0","Hf","MM","R","Tlimit","ahigh","alow","bhigh","blow","name"};
struct record_description Modelica_Media_IdealGases_Common_DataRecord$CH4__desc = {
  "Modelica_Media_IdealGases_Common_DataRecord$CH4", /* package_record__X */
  "Modelica.Media.IdealGases.Common.DataRecord$CH4", /* package.record_X */
  Modelica_Media_IdealGases_Common_DataRecord$CH4__desc__fields
};

#define Modelica_Media_IdealGases_Common_DataRecord$CL2__desc_added 1
const char* Modelica_Media_IdealGases_Common_DataRecord$CL2__desc__fields[10] = {"H0","Hf","MM","R","Tlimit","ahigh","alow","bhigh","blow","name"};
struct record_description Modelica_Media_IdealGases_Common_DataRecord$CL2__desc = {
  "Modelica_Media_IdealGases_Common_DataRecord$CL2", /* package_record__X */
  "Modelica.Media.IdealGases.Common.DataRecord$CL2", /* package.record_X */
  Modelica_Media_IdealGases_Common_DataRecord$CL2__desc__fields
};

#define Modelica_Media_IdealGases_Common_DataRecord$CO__desc_added 1
const char* Modelica_Media_IdealGases_Common_DataRecord$CO__desc__fields[10] = {"H0","Hf","MM","R","Tlimit","ahigh","alow","bhigh","blow","name"};
struct record_description Modelica_Media_IdealGases_Common_DataRecord$CO__desc = {
  "Modelica_Media_IdealGases_Common_DataRecord$CO", /* package_record__X */
  "Modelica.Media.IdealGases.Common.DataRecord$CO", /* package.record_X */
  Modelica_Media_IdealGases_Common_DataRecord$CO__desc__fields
};

#define Modelica_Media_IdealGases_Common_DataRecord$CO2__desc_added 1
const char* Modelica_Media_IdealGases_Common_DataRecord$CO2__desc__fields[10] = {"H0","Hf","MM","R","Tlimit","ahigh","alow","bhigh","blow","name"};
struct record_description Modelica_Media_IdealGases_Common_DataRecord$CO2__desc = {
  "Modelica_Media_IdealGases_Common_DataRecord$CO2", /* package_record__X */
  "Modelica.Media.IdealGases.Common.DataRecord$CO2", /* package.record_X */
  Modelica_Media_IdealGases_Common_DataRecord$CO2__desc__fields
};

#define Modelica_Media_IdealGases_Common_DataRecord$F2__desc_added 1
const char* Modelica_Media_IdealGases_Common_DataRecord$F2__desc__fields[10] = {"H0","Hf","MM","R","Tlimit","ahigh","alow","bhigh","blow","name"};
struct record_description Modelica_Media_IdealGases_Common_DataRecord$F2__desc = {
  "Modelica_Media_IdealGases_Common_DataRecord$F2", /* package_record__X */
  "Modelica.Media.IdealGases.Common.DataRecord$F2", /* package.record_X */
  Modelica_Media_IdealGases_Common_DataRecord$F2__desc__fields
};

#define Modelica_Media_IdealGases_Common_DataRecord$H2__desc_added 1
const char* Modelica_Media_IdealGases_Common_DataRecord$H2__desc__fields[10] = {"H0","Hf","MM","R","Tlimit","ahigh","alow","bhigh","blow","name"};
struct record_description Modelica_Media_IdealGases_Common_DataRecord$H2__desc = {
  "Modelica_Media_IdealGases_Common_DataRecord$H2", /* package_record__X */
  "Modelica.Media.IdealGases.Common.DataRecord$H2", /* package.record_X */
  Modelica_Media_IdealGases_Common_DataRecord$H2__desc__fields
};

#define Modelica_Media_IdealGases_Common_DataRecord$H2O__desc_added 1
const char* Modelica_Media_IdealGases_Common_DataRecord$H2O__desc__fields[10] = {"H0","Hf","MM","R","Tlimit","ahigh","alow","bhigh","blow","name"};
struct record_description Modelica_Media_IdealGases_Common_DataRecord$H2O__desc = {
  "Modelica_Media_IdealGases_Common_DataRecord$H2O", /* package_record__X */
  "Modelica.Media.IdealGases.Common.DataRecord$H2O", /* package.record_X */
  Modelica_Media_IdealGases_Common_DataRecord$H2O__desc__fields
};

#define Modelica_Media_IdealGases_Common_DataRecord$He__desc_added 1
const char* Modelica_Media_IdealGases_Common_DataRecord$He__desc__fields[10] = {"H0","Hf","MM","R","Tlimit","ahigh","alow","bhigh","blow","name"};
struct record_description Modelica_Media_IdealGases_Common_DataRecord$He__desc = {
  "Modelica_Media_IdealGases_Common_DataRecord$He", /* package_record__X */
  "Modelica.Media.IdealGases.Common.DataRecord$He", /* package.record_X */
  Modelica_Media_IdealGases_Common_DataRecord$He__desc__fields
};

#define Modelica_Media_IdealGases_Common_DataRecord$N2__desc_added 1
const char* Modelica_Media_IdealGases_Common_DataRecord$N2__desc__fields[10] = {"H0","Hf","MM","R","Tlimit","ahigh","alow","bhigh","blow","name"};
struct record_description Modelica_Media_IdealGases_Common_DataRecord$N2__desc = {
  "Modelica_Media_IdealGases_Common_DataRecord$N2", /* package_record__X */
  "Modelica.Media.IdealGases.Common.DataRecord$N2", /* package.record_X */
  Modelica_Media_IdealGases_Common_DataRecord$N2__desc__fields
};

#define Modelica_Media_IdealGases_Common_DataRecord$N2O__desc_added 1
const char* Modelica_Media_IdealGases_Common_DataRecord$N2O__desc__fields[10] = {"H0","Hf","MM","R","Tlimit","ahigh","alow","bhigh","blow","name"};
struct record_description Modelica_Media_IdealGases_Common_DataRecord$N2O__desc = {
  "Modelica_Media_IdealGases_Common_DataRecord$N2O", /* package_record__X */
  "Modelica.Media.IdealGases.Common.DataRecord$N2O", /* package.record_X */
  Modelica_Media_IdealGases_Common_DataRecord$N2O__desc__fields
};

#define Modelica_Media_IdealGases_Common_DataRecord$NH3__desc_added 1
const char* Modelica_Media_IdealGases_Common_DataRecord$NH3__desc__fields[10] = {"H0","Hf","MM","R","Tlimit","ahigh","alow","bhigh","blow","name"};
struct record_description Modelica_Media_IdealGases_Common_DataRecord$NH3__desc = {
  "Modelica_Media_IdealGases_Common_DataRecord$NH3", /* package_record__X */
  "Modelica.Media.IdealGases.Common.DataRecord$NH3", /* package.record_X */
  Modelica_Media_IdealGases_Common_DataRecord$NH3__desc__fields
};

#define Modelica_Media_IdealGases_Common_DataRecord$NO__desc_added 1
const char* Modelica_Media_IdealGases_Common_DataRecord$NO__desc__fields[10] = {"H0","Hf","MM","R","Tlimit","ahigh","alow","bhigh","blow","name"};
struct record_description Modelica_Media_IdealGases_Common_DataRecord$NO__desc = {
  "Modelica_Media_IdealGases_Common_DataRecord$NO", /* package_record__X */
  "Modelica.Media.IdealGases.Common.DataRecord$NO", /* package.record_X */
  Modelica_Media_IdealGases_Common_DataRecord$NO__desc__fields
};

#define Modelica_Media_IdealGases_Common_DataRecord$NO2__desc_added 1
const char* Modelica_Media_IdealGases_Common_DataRecord$NO2__desc__fields[10] = {"H0","Hf","MM","R","Tlimit","ahigh","alow","bhigh","blow","name"};
struct record_description Modelica_Media_IdealGases_Common_DataRecord$NO2__desc = {
  "Modelica_Media_IdealGases_Common_DataRecord$NO2", /* package_record__X */
  "Modelica.Media.IdealGases.Common.DataRecord$NO2", /* package.record_X */
  Modelica_Media_IdealGases_Common_DataRecord$NO2__desc__fields
};

#define Modelica_Media_IdealGases_Common_DataRecord$Ne__desc_added 1
const char* Modelica_Media_IdealGases_Common_DataRecord$Ne__desc__fields[10] = {"H0","Hf","MM","R","Tlimit","ahigh","alow","bhigh","blow","name"};
struct record_description Modelica_Media_IdealGases_Common_DataRecord$Ne__desc = {
  "Modelica_Media_IdealGases_Common_DataRecord$Ne", /* package_record__X */
  "Modelica.Media.IdealGases.Common.DataRecord$Ne", /* package.record_X */
  Modelica_Media_IdealGases_Common_DataRecord$Ne__desc__fields
};

#define Modelica_Media_IdealGases_Common_DataRecord$O2__desc_added 1
const char* Modelica_Media_IdealGases_Common_DataRecord$O2__desc__fields[10] = {"H0","Hf","MM","R","Tlimit","ahigh","alow","bhigh","blow","name"};
struct record_description Modelica_Media_IdealGases_Common_DataRecord$O2__desc = {
  "Modelica_Media_IdealGases_Common_DataRecord$O2", /* package_record__X */
  "Modelica.Media.IdealGases.Common.DataRecord$O2", /* package.record_X */
  Modelica_Media_IdealGases_Common_DataRecord$O2__desc__fields
};

#define Modelica_Media_IdealGases_Common_DataRecord$SO2__desc_added 1
const char* Modelica_Media_IdealGases_Common_DataRecord$SO2__desc__fields[10] = {"H0","Hf","MM","R","Tlimit","ahigh","alow","bhigh","blow","name"};
struct record_description Modelica_Media_IdealGases_Common_DataRecord$SO2__desc = {
  "Modelica_Media_IdealGases_Common_DataRecord$SO2", /* package_record__X */
  "Modelica.Media.IdealGases.Common.DataRecord$SO2", /* package.record_X */
  Modelica_Media_IdealGases_Common_DataRecord$SO2__desc__fields
};

#define Modelica_Media_IdealGases_Common_DataRecord$SO3__desc_added 1
const char* Modelica_Media_IdealGases_Common_DataRecord$SO3__desc__fields[10] = {"H0","Hf","MM","R","Tlimit","ahigh","alow","bhigh","blow","name"};
struct record_description Modelica_Media_IdealGases_Common_DataRecord$SO3__desc = {
  "Modelica_Media_IdealGases_Common_DataRecord$SO3", /* package_record__X */
  "Modelica.Media.IdealGases.Common.DataRecord$SO3", /* package.record_X */
  Modelica_Media_IdealGases_Common_DataRecord$SO3__desc__fields
};

#ifdef __cplusplus
}
#endif

