/* Additional record code for OpenModelica_Scripting_setInitXmlStartValue generated by the OpenModelica Compiler OpenModelica v1.11.0 (64-bit). */

#include "meta/meta_modelica.h"

#ifdef __cplusplus
extern "C" {
#endif

#define OpenModelica_Scripting_CheckSettingsResult__desc_added 1
const char* OpenModelica_Scripting_CheckSettingsResult__desc__fields[18] = {"CONFIGURE_CMDLINE","CREATE_FILE_WORKS","C_COMPILER","C_COMPILER_RESPONDING","C_COMPILER_VERSION","HAVE_CORBA","MODELICAUSERCFLAGS","OMC_FOUND","OMC_PATH","OMDEV_PATH","OPENMODELICAHOME","OPENMODELICALIBRARY","OS","REMOVE_FILE_WORKS","SENDDATALIBS","SYSTEM_INFO","SYSTEM_PATH","WORKING_DIRECTORY"};
struct record_description OpenModelica_Scripting_CheckSettingsResult__desc = {
  "OpenModelica_Scripting_CheckSettingsResult", /* package_record__X */
  "OpenModelica.Scripting.CheckSettingsResult", /* package.record_X */
  OpenModelica_Scripting_CheckSettingsResult__desc__fields
};

#ifdef __cplusplus
}
#endif

