/* Additional record code for test1 generated by the OpenModelica Compiler OpenModelica v1.11.0 (64-bit). */

#include "meta/meta_modelica.h"

#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
}
#endif

