# Makefile generated by OpenModelica

# Simulations use -O3 by default
CC=gcc
CXX=g++
LINK=g++ -shared -Xlinker --export-all-symbols -fPIC
EXEEXT=.exe
DLLEXT=.dll
CFLAGS_BASED_ON_INIT_FILE=
DEBUG_FLAGS=
CFLAGS=$(CFLAGS_BASED_ON_INIT_FILE) $(DEBUG_FLAGS) ${SIM_OR_DYNLOAD_OPT_LEVEL} -falign-functions -msse2 -mfpmath=sse ${MODELICAUSERCFLAGS}    
CPPFLAGS= -I"C:/OpenModelica1.11.0-64bit//include/omc/c" -I. -DOPENMODELICA_XML_FROM_FILE_AT_RUNTIME -DOMC_MODEL_PREFIX=test1 -DOMC_NUM_MIXED_SYSTEMS=0 -DOMC_NUM_LINEAR_SYSTEMS=0 -DOMC_NUM_NONLINEAR_SYSTEMS=0 -DOMC_NDELAY_EXPRESSIONS=0 -DOMC_NVAR_STRING=0
LDFLAGS=-L"C:/Work/CAE/Modelica/OpenModelica/OpenModelica_Excel_Interface_ClassPackage/Examples/Test/parameterSweep/5" -L"C:/OpenModelica1.11.0-64bit//lib//omc" -L"C:/OpenModelica1.11.0-64bit//lib" -Wl,--stack,16777216,-rpath,"C:/OpenModelica1.11.0-64bit//lib//omc" -Wl,-rpath,"C:/OpenModelica1.11.0-64bit//lib"   -lregex -lexpat -lomcgc -lpthread -fopenmp -loleaut32 -lz -lhdf5  -lSimulationRuntimeC -lomcgc -lexpat -lregex -static-libgcc -luuid -loleaut32 -lole32 -lws2_32 -llis -lumfpack -lklu -lcolamd -lbtf -lamd -lsundials_idas -lsundials_kinsol -lsundials_nvecserial -lipopt -lcoinmumps -lpthread -lm -lgfortranbegin -lgfortran -lmingw32 -lgcc_eh -lmoldname -lmingwex -lmsvcrt -luser32 -lkernel32 -ladvapi32 -lshell32 -lopenblas -lcminpack -lwsock32 -lstdc++ 
MAINFILE=test1.c
MAINOBJ=test1.o
CFILES=test1_functions.c test1_records.c \
test1_01exo.c test1_02nls.c test1_03lsy.c test1_04set.c test1_05evt.c test1_06inz.c test1_07dly.c \
test1_08bnd.c test1_09alg.c test1_10asr.c test1_11mix.c test1_12jac.c test1_13opt.c test1_14lnz.c \
test1_15syn.c test1_16dae.c
OFILES=$(CFILES:.c=.o)
GENERATEDFILES=$(MAINFILE) test1.makefile test1_literals.h test1_functions.h $(CFILES)

.PHONY: omc_main_target clean bundle

# This is to make sure that test1_*.c are always compiled.
.PHONY: $(CFILES)

omc_main_target: $(MAINOBJ) test1_functions.h test1_literals.h $(OFILES)
	$(CC) -I. -o test1$(EXEEXT) $(MAINOBJ) $(OFILES) $(CPPFLAGS) -L"C:/Work/CAE/Modelica/OpenModelica/OpenModelica_Excel_Interface_ClassPackage/Examples/Test/parameterSweep/5"   $(CFLAGS) $(CPPFLAGS) $(LDFLAGS)
clean:
	@rm -f test1_records.o $(MAINOBJ)

bundle:
	@tar -cvf test1_Files.tar $(GENERATEDFILES)